# Generated by Django 3.2.4 on 2021-06-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeFeed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question_name',
        ),
    ]
